version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:password@db:3306/ai_quizzer
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - GROQ_API_KEY=your-groq-api-key
      - REDIS_URL=redis://redis:6379
      - EMAIL_SERVICE=gmail
      - EMAIL_USER=your-email@gmail.com
      - EMAIL_PASS=your-app-password
      - FRONTEND_URL=http://localhost:3000
      - API_URL=http://localhost:4000
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ai_quizzer
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
